### ISSUE TITLE
Wrap all with folder Symfony2

### ISSUE THREAD

**Issue by brunowego** [escapestudios/Symfony2-coding-standard#14]
I think will be better if wrap this inside folder Symfony2, example:

```bash
git clone git://github.com/escapestudios/Symfony2-coding-standard.git Symfony2
```

**Comment by djoos** [comment]
Hi @brunowego,

thanks for getting in touch!

I'm not 100% what you mean exactly, would you mind giving some further information?

Thanks in advance!

Kind regards,
David

**Comment by brunowego** [comment]
Sorry for that.

I will try explain better, at this moment when user clone this repo, the full project will be save in folder `/usr/local/Cellar/php-code-sniffer/2.2.0/CodeSniffer/Standards`, but files like .gitignore, .travis.yml, CONTRIBUTING.md, etc., will be save in the folder `Standards`.

**Comment by djoos** [comment]
Hi Bruno,

ah ok, I got it now. If you want to checkout the coding standard in the Standards-directory you'll have to clean up the additional files - alternatively just check out the standard to any folder on your system and make use of phpcs --config-set installed_paths /path/to/Symfony2-coding-standard which will add the standard (you can use phpcs -i to confirm afterwards) without having to move it to the Standards folder...

Hope this helps!

Kind regards,
David

**Comment by Craige** [comment]
@brunowego - The reason for the new format is partially to to accommodate installing the standard as part of a Composer project, but also to make sure that the standard always exists under a folder with the name of the standard.

When installing Symfony2-coding-standards automatically through composer, you do not get to specify the target directory like you do when just cloning the project through git. Because of this, the ruleset.xml doesn't exist in a folder with the name of the standard (in our case, "Symfony2"), which causes a problem for PHP_CodeSniffer. We want the ruleset.xml and Sniffs to always exist in a folder named Symfony2, but the default functionality of git is to check it out into a folder with the name of the repository "Symfony2-coding-standard". We had to get around that.

The best approach if you want to install the standard into PHP_CodeSniffer's Standards to directory is to clone this repository somewhere sensical and symlink the Symfony2 directory to the Standards directory. Alternatively, you could check out this repository somewhere, and set phpcs's `installed_paths` directive to append this new path.

Does this make sense?

**Comment by Craige** [comment]
Actually, I think @brunowego has a point that we should address. Users are unable to check out this repository as is described in the PHP_CodeSniffer documentation (which is adding new Standards directly to the Standard directory). This is an easy enough fix, and I've implemented it and [initiated a PR](https://github.com/escapestudios/Symfony2-coding-standard/pull/16)

**Comment by brunowego** [comment]
:+1:

**Comment by djoos** [comment]
Hi guys,

I've opted for making the installation section in the [README.md](https://github.com/escapestudios/Symfony2-coding-standard/blob/master/README.md) more clear. Thanks for your help with that in #13 @Craige!

I'll close this issue for now, but do let me know if you have any further remarks or comments!

Kind regards,
David
